// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ventas.Moldels
{
    public partial class Clientes
    {
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public int? FkProducto { get; set; }
        public int? FkMediosPagos { get; set; }

        public virtual MediosPagos FkMediosPagosNavigation { get; set; }
        public virtual Productos FkProductoNavigation { get; set; }
    }
}