// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ventas.Moldels
{
    public partial class MediosPagos
    {
        public MediosPagos()
        {
            Clientes = new HashSet<Clientes>();
        }

        public int Id { get; set; }
        public string MedioPago { get; set; }

        public virtual ICollection<Clientes> Clientes { get; set; }
    }
}